stages:
  - deploy

deploy_to_heroku:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache curl bash
    - curl https://cli-assets.heroku.com/install.sh | /bin/bash
    - export PATH="/usr/local/bin:$PATH"
  script:
    - echo "Deploying to Heroku..."
    - heroku auth:token
    - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/staff-helper.git HEAD:main
  only:
    - main
  when: manual
